# Generated by Django 5.1.6 on 2025-02-13 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
