# Generated by Django 5.1.6 on 2025-02-14 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_picture',
        ),
    ]
