# Generated by Django 5.1.6 on 2025-02-14 08:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_alter_review_rating_alter_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
