# Generated by Django 5.1.6 on 2025-02-14 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='book_files/'),
        ),
    ]
