# Generated by Django 5.1.6 on 2025-02-14 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_chapter_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ['number']},
        ),
        migrations.AddField(
            model_name='chapter',
            name='number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chapter_files/'),
        ),
    ]
